export const TO_RECEIVE_MOCK_DATA = [
  {
    nTitulo: '14',
    situacao: 'Quitado',
    formPgto: 'Cartão de Crédito',
    titular: 'Maria Aparecida Oliveira',
    vencimento: new Date(2014, 1, 1),
    pagamento: new Date(2014, 1, 1),
    referente: 'Anúncio - 05/2018',
    original: 25.00,
    acrescimo: 0,
    decrescimo: 0,
  },
  {
    nTitulo: '15',
    situacao: 'Quitado',
    formPgto: 'Boleto',
    titular: 'Jose Antonio dos Santos',
    vencimento: new Date(2014, 1, 1),
    pagamento: new Date(2014, 1, 1),
    referente: 'Anúncio - 05/2018',
    original: 25.00,
    acrescimo: 0,
    decrescimo: 0,
  },
  {
    nTitulo: '14',
    situacao: 'Pendente',
    formPgto: 'Boleto',
    titular: 'Lucia da Silva',
    vencimento: new Date(2014, 1, 1),
    pagamento: new Date(2014, 1, 1),
    referente: 'Anúncio - 05/2018',
    original: 25.00,
    acrescimo: 0,
    decrescimo: 0,
  },
  {
    nTitulo: '56',
    situacao: 'Pendente',
    formPgto: 'Boleto',
    titular: 'Sonia Regina Ricardo',
    vencimento: new Date(2014, 1, 1),
    pagamento: new Date(2014, 1, 1),
    referente: 'Anúncio - 05/2018',
    original: 25.00,
    acrescimo: 0,
    decrescimo: 0,
  }
];
