export const ABVR_ESTADO = {
  RJ: 'Rio de Janeiro',
  RO: 'Rondonia',
  AC: 'Acre',
  AM: 'Amazonas',
  RR: 'Roraima',
  PA: 'Para',
  TO: 'Tocantins',
  AP: 'Amapa',
  MA: 'Maranhao',
  PI: 'Piaui',
  CE: 'Ceara',
  RN: 'Rio Grande do Norte',
  PB: 'Paraiba',
  PE: 'Pernambuco',
  AL: 'Alagoas',
  SE: 'Sergipe',
  BA: 'Bahia',
  MG: 'Minas Gerais',
  ES: 'Espirito Santo',
  SP: 'Sao Paulo',
  PR: 'Parana',
  SC: 'Santa Catarina',
  RS: 'Rio Grande do Sul',
  MS: 'Mato Grosso do Sul',
  GO: 'Goias',
  MT: 'Mato Grosso',
  DF: 'Distrito Federal'
};

export const ABVR_ESTADO_INVERSO = {
  'Rio de Janeiro': 'RJ',
  Rondonia: 'RO',
  Acre: 'AC',
  Amazonas: 'AM',
  Roraima: 'RR',
  Para: 'PA',
  Tocantins: 'TO',
  Amapa: 'AP',
  Maranhao: 'MA',
  Piaui: 'PI',
  Ceara: 'CE',
  'Rio Grande do Norte': 'RN',
  Paraiba: 'PB',
  Pernambuco: 'PE',
  Alagoas: 'AL',
  Sergipe: 'SE',
  Bahia: 'BA',
  'Minas Gerais': 'MG',
  'Espirito Santo': 'ES',
  'Sao Paulo': 'SP',
  Parana: 'PR',
  'Santa Catarina': 'SC',
  'Rio Grande do Sul': 'RS',
  'Mato Grosso do Sul': 'MS',
  Goias: 'GO',
  'Mato Grosso': 'MT',
  'Distrito Federal': 'DF'
};

export const BR_STATE_INITIALS = [
  'RJ',
  'RO',
  'AC',
  'AM',
  'RR',
  'PA',
  'TO',
  'AP',
  'MA',
  'PI',
  'CE',
  'RN',
  'PB',
  'PE',
  'AL',
  'SE',
  'BA',
  'MG',
  'ES',
  'SP',
  'PR',
  'SC',
  'RS',
  'MS',
  'GO',
  'MT',
  'DF'
];
export const BR_STATE_NAMES = [
    'Rio de Janeiro',
    'Rondonia',
    'Acre',
    'Amazonas',
    'Roraima',
    'Para',
    'Tocantins',
    'Amapa',
    'Maranhao',
    'Piaui',
    'Ceara',
    'Rio Grande do Norte',
    'Paraiba',
    'Pernambuco',
    'Alagoas',
    'Sergipe',
    'Bahia',
    'Minas Gerais',
    'Espirito Santo',
    'Sao Paulo',
    'Parana',
    'Santa Catarina',
    'Rio Grande do Sul',
    'Mato Grosso do Sul',
    'Goias',
    'Mato Grosso',
    'Distrito Federal'
  ];
