export const CITYCODE = {
  'Rio de Janeiro': 33,
  'Rondonia': 11,
  'Acre': 12,
  'Amazonas': 13,
  'Roraima': 14,
  'Para': 15,
  'Tocantins': 17,
  'Amapa': 16,
  'Maranhao': 21,
  'Piaui': 22,
  'Ceara': 23,
  'Rio Grande do Norte': 24,
  'Paraiba': 25,
  'Pernambuco': 26,
  'Alagoas': 27,
  'Sergipe': 28,
  'Bahia': 29,
  'Minas Gerais': 31,
  'Espirito Santo': 32,
  'Sao Paulo': 35,
  'Parana': 41,
  'Santa Catarina': 42,
  'Rio Grande do Sul': 43,
  'Mato Grosso do Sul': 50,
  'Goias': 52,
  'Mato Grosso': 51,
  'Distrito Federal': 53
};
